version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receipt_assistant_backend
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./dist:/app/dist
      - /app/node_modules
    depends_on:
      - postgres
    command: pnpm dev
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: receipt_assistant_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-receiptdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge